// Use this file to write queries to test your data connector
let
    result = TagInformation.Contents("dev-internal.icube.co.th", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2Nlc3NfdG9rZW4iLCJ1c2VySWQiOiJEZW5zb19hcGkiLCJmYWN0b3J5SWQiOiIxIiwiZXhwIjoxNzcyMjQ2MTIwLCJpc3MiOiJpQ3ViZVNlcnZlciIsImF1ZCI6ImlDdWJlQ2xpZW50In0.ERZjvl4JZxI4F9BwqigjqPOimSVv1I001d9uA2b4aBo", "TagRelation", "Get all Tags", "a_test_view_view2")
in
    result
